#+TITLE: Dictator vs Me (vol 1): Culture
#+SUBTITLE: Fictional discussions between my dictator-ish alter-ego and.. me

#+DATE: <2020-09-23 Wed>

  - D: I feel like banning pop music.
  - M: Huh? Somebody woke up grumpy.
  - D: It's reggaeton that makes me grumpy. Up until recently you had
    dumb guys pumping up their music in their car and annoying the
    shit out of residents & people walking by.
  - M: OK, I'll give you that, it is annoying.
  - D: And now, you have people attaching portable speakers on them
    and cranking up the volume while walking or riding their
    bicycle. It's like Satan has discovered new ways of torture.
  - M: Sure, that's annoying as well. But what's up with the banning
    thing you said?
  - D: Well, look: 99% of the time people who do this will put on shitty
    pop music. Whatever pop is in that country. May it be reggaeton,
    may it be trap, you name it.
  - M: Go on..
  - D: So.. I just figured a solution. Whenever a genre becomes
    popular (in terms of what they play on the radio etc).. BAN IT!
    Make it illegal. Illegal for the radio, illegal for the
    bars. Illegal for the internet. Censor it, I don't know. You know
    what's funny? The individuals that "listen" to this music would
    never go into the trouble of searching for it. They consume
    because it's almost shoved down their throats. What on earth would
    those people put on their Bluetooth speaker then? I mean, if they
    go into the trouble of finding this now-illegal music.. good for
    them. I don't approve but, hey, since you like it so much I guess
    you have the right of annoying the rest of us from time to time.
  - [D continues] On the other hand, there are genres of music that
    people would not stop listening to even if they got
    illegal. The point I want to make is that the majority of the
    popular music would go extinct if it were to be illegal. People
    would not care to look for it. So.. why not extend this idea and
    "ban" everything that becomes popular? It's like a test.
  - M: I see. But, again, I think you woke up grumpy.
  - D: Yeah, it's my bed. Remind me to find the manufacturer later, I'll
    close down their company. [murmurs the following] Let's see if
    anyone would miss them.
