#+TITLE: (Poem) Αναπνοή | Breath | Respiración (gr|eng|es)
#+SUBTITLE: A poem in greek, english and spanish.
#+DATE: <2020-04-04 Sat>

Gracias a Julia por ayudar con la traducción.

* Αναπνοή
  #+BEGIN_VERSE
  Την τελευταία εβδομάδα η αναπνοή μου ήταν κουρασμένη.
  Αργόσυρτη κι ασθενική.

  Αλλά εκείνη τη νύχτα ήταν διαφορετική.
  Δεν καθόμασταν σε παραλία, αλλά ακουγόταν ο ήχος της θάλασσας.
  Εισπνοή, τα νερά αποτραβιούνται.
  Εκπνοή, σκάει το κύμα στην ακρογιαλιά, μπροστά στα πόδια μας.

  Και εμείς μιλούσαμε.
  Μιλούσαμε χωρίς σταματημό.
  Για την μοναξιά. Για την έμπνευση. Για λάθη που θα ξανακάναμε.
  Τι ωραία αυτά τα λάθη που μας οδήγησαν σε αυτήν την ακρογιαλιά.

  Και η θάλασσα να φουντώνει.
  Χύνεται αχαλίνωτη στην ακρογιαλιά.
  Εμείς βρεχόμαστε, και όλη η φύση τριγύρω ξυπνά από τα κύματα.
  Όλη η φύση στο πόδι.

  Και η ώρα πέρασε και τα μάτια μας έκλειναν.
  Και τελικά μας πήρε ο ύπνος.
  Και η θάλασσα σώπασε.
  #+END_VERSE

* Breath
#+BEGIN_VERSE
  The past week my breath had been kind of tired.
  Shallow, lacking vigor.

  But that night was different.
  The sea was nowhere near, but its sound was present.
  Inhale, the waters withdraw.
  Exhale, the wave crushes on the seashore, just touching the tip of our toes.

  And we were talking.
  Talking without stopping.
  About loneliness. About inspiration. Mistakes we'd gladly repeat.
  Oh how wonderful, these mistakes. Leading us to this very beach.

  And the sea is growing wild.
  Waters gushing down the shore.
  And we're getting wet, and the whole nature awakens by the sound of the waves.
  The whole nature alert.

  And time went by and our eyes grew tired.
  And, in the end, we slept.
  And eventually the sea got quiet.
  #+END_VERSE
  
* Respiración
  #+BEGIN_VERSE
  Durante la semana pasada, mi respiración tenía rasgos de estar cansada.
  Lenta y sin fuerza.

  Pero esta noche fue diferente.
  No estábamos sentados en una playa, pero aun así se escuchaba el mar.
  Inhalar, las aguas se retiran.
  Exhalar, las olas se rompen en la costa.

  Y hablábamos.
  Hablábamos sin parar.
  Sobre soledad. Sobre inspiración. Sobre errores que repetiríamos.
  ¡Oh, que errores tan maravillosos que nos guiaron aquí, a esta playa!

  Y el mar estaba estaba engrandeciéndose.
  Aguas irrumpen en la costa.
  Y nosotros nos mojábamos, y la naturaleza se despertó por el sonido de la olas.
  Toda la naturaleza en pie.

  El tiempo pasó y nuestros ojos se cerraban.
  Y, entonces, nos dormimos.
  Y, al fin, el mar se silenció.
  #+END_VERSE
